CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_type VARCHAR(10) NOT NULL CHECK (user_type IN ('farmer','buyer','admin')),
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crops (
    crop_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    crop_name VARCHAR(100) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'kg',
    price DECIMAL(12,2) NOT NULL,
    quality VARCHAR(50),
    location VARCHAR(150),
    harvest_date DATE,
    status VARCHAR(20) DEFAULT 'Available' CHECK (status IN ('Available','Sold','Unavailable')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    crop_id INTEGER NOT NULL REFERENCES crops(crop_id) ON DELETE CASCADE,
    quantity DECIMAL(12,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'Pending' CHECK (status IN ('Pending','Accepted','Rejected','Completed','Cancelled')),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_history (
    price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name VARCHAR(100) NOT NULL,
    market_price DECIMAL(12,2) NOT NULL,
    location VARCHAR(150),
    price_date DATE NOT NULL
);

INSERT INTO price_history(crop_name,market_price,location,price_date)
SELECT * FROM (VALUES
('Tomato',24,'Bengaluru','2026-09-20'::date),
('Tomato',25,'Bengaluru','2026-09-21'::date),
('Tomato',26,'Bengaluru','2026-09-22'::date),
('Onion',28,'Bengaluru','2026-09-20'::date),
('Onion',30,'Bengaluru','2026-09-21'::date),
('Onion',29,'Bengaluru','2026-09-22'::date),
('Potato',22,'Bengaluru','2026-09-20'::date),
('Potato',24,'Bengaluru','2026-09-21'::date),
('Potato',23,'Bengaluru','2026-09-22'::date)
) AS v(crop_name,market_price,location,price_date)
WHERE NOT EXISTS (SELECT 1 FROM price_history);

-- Create admin after installation. Generate a password hash with Python/Werkzeug.
